### ISSUE TITLE
如何自定义 koni 锚点 click 事件，以及自定义锚点样式？ 

### ISSUE THREAD

**Issue by Draco-china** [antvis/g6-editor#91]
1. 尝试了好久都没有找到自定义 koni 锚点 click 自定义的方式
2. koni 锚点的样式也没有找到对应的修改方式 以下是个人暂时使用的方法自定义样式
```javascript
const anchorDom = editor.getCurrentPage().get('_controllers').orbit.satelliteCache[0].dom
anchorDom.setAttribute('style', '')
anchorDom.setAttribute('class', 'anchor-icon')
```

```css
.anchor-icon {
    position: absolute;
    width: 11px;
    height: 11px;
    cursor: copy;
    background-image: url(./svg/add.svg)
 }
```
希望能告知 koni 锚点自定义 click事件的方法，谢谢🙏
